/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package symbiosis.meta.objectmodel;

import symbiosis.meta.requirements.RuleRequirement;
import symbiosis.meta.traceability.ParentElement;
import java.io.Serializable;

/**
 *
 * @author frankpeeters
 */
public class AutoIncrConstraint extends StaticConstraint implements Serializable {

    private static final long serialVersionUID = 1L;

    public AutoIncrConstraint(ParentElement parent, RuleRequirement rule) {
        super(parent, rule);
    }

    @Override
    public String getAbbreviationCode() {
        return "incr";
    }

    @Override
    public boolean isRealized() {
        return true;
    }

    @Override
    public FactType getFactType() {
        return (FactType) getParent().getParent();
    }

    @Override
    public String getRequirementText() {
        BaseValueRole role = (BaseValueRole) getParent();
        
        return "The value of " + role.getRoleName() + " in <" + getFactType().getName() + "> is generated by auto increment.";
    }
}
