/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ConfirmationDialog.java
 *
 * Created on 6-jun-2011, 17:27:38
 */
package equa.factbreakdown.gui;

import java.awt.FlowLayout;

import javax.swing.JOptionPane;

/**
 *
 * @author FrankP
 */
public class ObscureValueLeafDialog extends javax.swing.JDialog {

    private static final long serialVersionUID = 1L;
    private boolean confirmed;
    private final String typeName;

    /**
     * Creates new form ConfirmationDialog
     * @param parent
     * @param modal
     * @param expression
     * @param roleName
     * @param typeName
     */
    public ObscureValueLeafDialog(java.awt.Frame parent, boolean modal,
            String expression, String roleName, String typeName) {
        super(parent, modal);
        initComponents();
        this.typeName = typeName;

        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                confirmed = false;
                setVisible(false);
            }
        });

        if (roleName.isEmpty()) {
            taQuestion.setText("Is \'" + expression + "\' a correct "
                    + "substitution in behalf of type \'"
                    + typeName + "\'?");
        } else {
            taQuestion.setText("Is \'" + expression + "\' a correct \'"
                    + roleName + "\' substitution in behalf of role \'"
                    + roleName + "\'?");
        }

        confirmed = false;
        setSize(500, 120);
        setLocation(400, 300);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnButtons = new javax.swing.JPanel(new FlowLayout(FlowLayout.RIGHT));
        btYes = new javax.swing.JButton();
        btNo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taQuestion = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        pnButtons.setName("pnButtons"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(ObscureValueLeafDialog.class);
        btYes.setText(resourceMap.getString("btYes.text")); // NOI18N
        btYes.setName("btYes"); // NOI18N
        btYes.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btYesActionPerformed(evt);
            }
        });
        pnButtons.add(btYes);

        btNo.setText(resourceMap.getString("btNo.text")); // NOI18N
        btNo.setName("btNo"); // NOI18N
        btNo.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNoActionPerformed(evt);
            }
        });
        pnButtons.add(btNo);

        getContentPane().add(pnButtons, java.awt.BorderLayout.SOUTH);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        taQuestion.setColumns(20);
        taQuestion.setEditable(false);
        taQuestion.setFont(resourceMap.getFont("taQuestion.font")); // NOI18N
        taQuestion.setLineWrap(true);
        taQuestion.setRows(5);
        taQuestion.setWrapStyleWord(true);
        taQuestion.setName("taQuestion"); // NOI18N
        jScrollPane1.setViewportView(taQuestion);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btYesActionPerformed
        confirmed = true;
        setVisible(false);
    }//GEN-LAST:event_btYesActionPerformed

    private void btNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNoActionPerformed
        confirmed = false;
        setVisible(false);
//        JOptionPane.showMessageDialog(getParent(), "You are invited to adjust the Object Type Expression of "
//                + typeName + " (see Type Configuration).");
    }//GEN-LAST:event_btNoActionPerformed

    public boolean isConfirmed() {
        return confirmed;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btNo;
    private javax.swing.JButton btYes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnButtons;
    private javax.swing.JTextArea taQuestion;
    // End of variables declaration//GEN-END:variables
}
