/*
 * LoginDialog.java
 *
 * Created on 18-mei-2012, 15:43:17
 */
package equa.project.dialog;

import javax.swing.JOptionPane;

import equa.controller.IView;
import equa.controller.ProjectController;
import equa.project.ProjectRole;
import java.awt.Frame;

/**
 *
 * @author teun
 */
@SuppressWarnings("serial")
public class LoginDialog extends javax.swing.JDialog implements IView {

    private final ProjectController projectController;

    /**
     * Creates new form LoginDialog
     *
     * @param parent
     * @param modal
     * @param controller
     */
    public LoginDialog(java.awt.Frame parent, boolean modal, ProjectController controller) {
        super(parent, modal);
        projectController = controller;
        projectController.addView(this);
        initComponents();
        this.setLocationRelativeTo(parent);
        ProjectRole p = (ProjectRole) cbProjectRoles.getItemAt(0);
        if (controller.getCurrentUser() != null && 
            cbProjectRoles.getItemCount() > 1 && 
            p.equals(controller.getCurrentUser())) {
            p = (ProjectRole) cbProjectRoles.getItemAt(1);
        }
        cbProjectRoles.setSelectedItem(p);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btOK = new javax.swing.JButton();
        pnUser = new javax.swing.JPanel();
        lblMessage = new javax.swing.JLabel();
        lblParticipant = new javax.swing.JLabel();
        cbProjectRoles = new javax.swing.JComboBox();
        btCancel = new javax.swing.JButton();
        btNew = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Select your name");
        setName("LoginDialog"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        btOK.setText("Continue");
        btOK.setToolTipText("Continue opening the project.");
        btOK.setName("btOK"); // NOI18N
        btOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOKActionPerformed(evt);
            }
        });

        pnUser.setBorder(javax.swing.BorderFactory.createTitledBorder("User"));
        pnUser.setName("pnUser"); // NOI18N

        lblMessage.setText("Please select your name from the list below.");
        lblMessage.setName("lblMessage"); // NOI18N

        lblParticipant.setText("Project role:");
        lblParticipant.setName("lblParticipant"); // NOI18N

        cbProjectRoles.setModel(projectController.getProject().getParticipants());
        cbProjectRoles.setName("cbProjectRoles"); // NOI18N

        javax.swing.GroupLayout pnUserLayout = new javax.swing.GroupLayout(pnUser);
        pnUser.setLayout(pnUserLayout);
        pnUserLayout.setHorizontalGroup(
            pnUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnUserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMessage)
                    .addComponent(lblParticipant))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnUserLayout.createSequentialGroup()
                    .addContainerGap(94, Short.MAX_VALUE)
                    .addComponent(cbProjectRoles, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        pnUserLayout.setVerticalGroup(
            pnUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnUserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMessage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblParticipant)
                .addContainerGap(13, Short.MAX_VALUE))
            .addGroup(pnUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnUserLayout.createSequentialGroup()
                    .addContainerGap(32, Short.MAX_VALUE)
                    .addComponent(cbProjectRoles, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        btCancel.setText("Cancel");
        btCancel.setToolTipText("Cancel opening the project");
        btCancel.setName("btCancel"); // NOI18N
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelActionPerformed(evt);
            }
        });

        btNew.setText("New");
        btNew.setName("btNew"); // NOI18N
        btNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(btNew)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btOK)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btCancel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCancel)
                    .addComponent(btOK)
                    .addComponent(btNew))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btOKActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btOKActionPerformed
    {//GEN-HEADEREND:event_btOKActionPerformed
        if (cbProjectRoles.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Please select your project role.");
        } else {
            projectController.setCurrentUser((ProjectRole) cbProjectRoles.getSelectedItem());
            projectController.removeView(this);
            setVisible(false);
        }
    }//GEN-LAST:event_btOKActionPerformed

    private void btCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelActionPerformed
       // cbProjectRoles.setSelectedItem(null);
        projectController.removeView(this);
        setVisible(false);
    }//GEN-LAST:event_btCancelActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosing
    {//GEN-HEADEREND:event_formWindowClosing
      //  cbProjectRoles.setSelectedItem(null);
        projectController.removeView(this);
        setVisible(false);
    }//GEN-LAST:event_formWindowClosing

    private void btNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNewActionPerformed
        Frame parent = (Frame) getParent();
        AddParticipantDialog pd = new AddParticipantDialog(parent, null, projectController);
        setVisible(false);
        pd.setVisible(true);
        (new LoginDialog(parent, true, projectController)).setVisible(true);
    }//GEN-LAST:event_btNewActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancel;
    private javax.swing.JButton btNew;
    private javax.swing.JButton btOK;
    private javax.swing.JComboBox cbProjectRoles;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblParticipant;
    private javax.swing.JPanel pnUser;
    // End of variables declaration//GEN-END:variables

    @Override
    public void refresh() {
        // No refresh needed
    }
}
