/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewProjectPage.java
 *
 * Created on 24-nov-2011, 14:58:49
 */
package equa.project.dialog;

import java.awt.Dimension;
import java.util.ArrayList;
import java.util.Map;

import javax.swing.ButtonGroup;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JLabel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.event.CaretEvent;
import javax.swing.event.CaretListener;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

import org.netbeans.spi.wizard.WizardController;

/**
 *
 * @author Keethanjan
 */
public class NewProjectPage extends javax.swing.JPanel {

    private static final long serialVersionUID = 1L;
    final WizardController controller;
    final Map<String, Object> settings;
    private ArrayList<JTextField> inputFields;
    private JRadioButton rdbtnProjectMember;
    private JRadioButton rdbtnStakeholder;

    /**
     * Creates new form NewProjectPage
     */
    public NewProjectPage(final WizardController controller, final Map<String, Object> settings) {
        initComponents();
        this.controller = controller;
        this.settings = settings;
        inputFields = new ArrayList<>();

        setMinimumSize(new Dimension(450, 115));
        setMaximumSize(new Dimension(450, 115));

        inputFields.add(nameTextField);
        inputFields.add(creatorTextField);
        inputFields.add(roleTextField);
        nameTextField.addCaretListener(createCaretListener("name", nameTextField, "Name must be entered"));
        creatorTextField.addCaretListener(createCaretListener("creator", creatorTextField, "The name of the creator must be entered"));
        roleTextField.addCaretListener(createCaretListener("role", roleTextField, "The role of the creator must be entered"));
        settings.put("projectmember", rdbtnProjectMember.isSelected());
        rdbtnProjectMember.addChangeListener(new ChangeListener() {

            @Override
            public void stateChanged(ChangeEvent e) {
                settings.put("projectmember", rdbtnProjectMember.isSelected());
            }
        });
    }

    /**
     * Create a caretListener for a textfield in the wizard. This caretListener
     * adds the textinput to the settings list. If the textinput is empty a
     * problem is set in the controller.
     *
     * @param fieldName The name used to identify the textinput in the settings
     * list.
     * @param fieldInput The text inputField the user used in the wizard.
     * @param errorDescription The error displayed if the input is empty.
     * @return Returns the CaretListener object.
     */
    private CaretListener createCaretListener(final String fieldName, final JTextField fieldInput, final String errorDescription) {
        return new CaretListener() {
            @Override
            public void caretUpdate(CaretEvent e) {
                settings.put(fieldName, fieldInput.getText());

                if (fieldInput.getText().isEmpty()) {
                    controller.setProblem(errorDescription);
                } else //If all textfields are filled enable the finish/continue button.
                {
                    boolean noMoreProblems = true;
                    for (JTextField field : inputFields) {
                        if (field.getText().isEmpty()) {
                            noMoreProblems = false;
                        }
                    }
                    if (noMoreProblems) {
                        controller.setProblem(null);
                    }
                }
            }
        };
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameTextField = new javax.swing.JTextField();
        nameLabel = new javax.swing.JLabel();
        creatorTextField = new javax.swing.JTextField();
        creatorLabel = new javax.swing.JLabel();
        roleLabel = new javax.swing.JLabel();
        roleTextField = new javax.swing.JTextField();

        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(NewProjectPage.class);
        nameTextField.setText(resourceMap.getString("nameTextField.text")); // NOI18N
        nameTextField.setName("nameTextField"); // NOI18N

        nameLabel.setText(resourceMap.getString("nameLabel.text")); // NOI18N
        nameLabel.setName("nameLabel"); // NOI18N

        creatorTextField.setName("creatorTextField"); // NOI18N

        creatorLabel.setText(resourceMap.getString("creatorLabel.text")); // NOI18N
        creatorLabel.setName("creatorLabel"); // NOI18N

        roleLabel.setText(resourceMap.getString("roleLabel.text")); // NOI18N
        roleLabel.setName("roleLabel"); // NOI18N

        roleTextField.setName("roleTextField"); // NOI18N
        
        JLabel lblParticipateAs = new JLabel("Participate as:");
        
        rdbtnProjectMember = new JRadioButton("Project Member");
        rdbtnProjectMember.setSelected(true);
        
        rdbtnStakeholder = new JRadioButton("Stakeholder");

        ButtonGroup group = new ButtonGroup();
        group.add(rdbtnProjectMember);
        group.add(rdbtnStakeholder);
        
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(lblParticipateAs, GroupLayout.PREFERRED_SIZE, 95, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addComponent(rdbtnProjectMember, GroupLayout.PREFERRED_SIZE, 135, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(rdbtnStakeholder, GroupLayout.PREFERRED_SIZE, 125, GroupLayout.PREFERRED_SIZE))
        				.addGroup(layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(nameLabel)
        						.addComponent(roleLabel)
        						.addComponent(creatorLabel))
        					.addGap(18)
        					.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        						.addComponent(nameTextField, GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
        						.addComponent(creatorTextField, GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
        						.addComponent(roleTextField, GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE))))
        			.addContainerGap())
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(nameTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(nameLabel))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(creatorTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(creatorLabel))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(roleTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(roleLabel))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(lblParticipateAs)
        				.addComponent(rdbtnProjectMember)
        				.addComponent(rdbtnStakeholder))
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        this.setLayout(layout);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify                     
    private javax.swing.JLabel creatorLabel;
    private javax.swing.JTextField creatorTextField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JLabel roleLabel;
    private javax.swing.JTextField roleTextField;
}
