/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package equa.project.dialog;

import equa.util.PreferenceOfAspect;
import java.awt.Color;
import javax.swing.JColorChooser;

/**
 *
 * @author frankpeeters
 */
public class PreferenceOfAspectDialog extends javax.swing.JDialog {

    private boolean ok;
    private Color background;
    private Color fontColor;

    /**
     * Creates new form PreferenceOfAspectDialog
     */
    public PreferenceOfAspectDialog(java.awt.Frame parent, PreferenceOfAspect poa, String title) {
        super(parent, true);
        setTitle(title);
        ok = false;
        background = poa.getBackground();
        fontColor = poa.getFontColor();
        initComponents();
    }

    public int getFontSize() {
        return Integer.parseInt(cbFontSize.getSelectedItem().toString());
    }

    public Color getBackground() {
        if (background == null) {
            return Color.white;
        } else {
            return background;
        }
    }

    public Color getFontColor() {
        if (fontColor == null) {
            return Color.black;
        } else {
            return fontColor;
        }
    }

    public boolean isOk() {
        return ok;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbFontSize = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        lbFontColor = new javax.swing.JLabel();
        lbBackground = new javax.swing.JLabel();
        btFontColor = new javax.swing.JButton();
        btBackground = new javax.swing.JButton();
        btCancel = new javax.swing.JButton();
        btOk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cbFontSize.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "10", "12", "14", "16", "18", "20", "22", "24" }));
        cbFontSize.setName("cbFontSize"); // NOI18N

        jLabel1.setText("Font Size");
        jLabel1.setName("jLabel1"); // NOI18N

        lbFontColor.setText("Font Color");
        lbFontColor.setName("lbFontColor"); // NOI18N

        lbBackground.setText("Background");
        lbBackground.setName("lbBackground"); // NOI18N

        btFontColor.setText("Choose");
        btFontColor.setName("btFontColor"); // NOI18N
        btFontColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFontColorActionPerformed(evt);
            }
        });

        btBackground.setText("Choose");
        btBackground.setName("btBackground"); // NOI18N
        btBackground.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBackgroundActionPerformed(evt);
            }
        });

        btCancel.setText("Cancel");
        btCancel.setName("btCancel"); // NOI18N
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelActionPerformed(evt);
            }
        });

        btOk.setText("Ok");
        btOk.setName("btOk"); // NOI18N
        btOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btOk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbBackground)
                            .addComponent(lbFontColor)
                            .addComponent(jLabel1))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(cbFontSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btBackground, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(btFontColor, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbFontSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbFontColor, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btFontColor))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbBackground)
                    .addComponent(btBackground))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCancel)
                    .addComponent(btOk))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOkActionPerformed
        ok = true;
        setVisible(false);
    }//GEN-LAST:event_btOkActionPerformed

    private void btCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelActionPerformed
        ok = false;
        setVisible(false);
    }//GEN-LAST:event_btCancelActionPerformed

    private void btFontColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFontColorActionPerformed

        JColorChooser colorChooser = new JColorChooser(Color.black);
        colorChooser.setVisible(true);
        fontColor =  JColorChooser.showDialog(getParent(), getTitle() + " font color", Color.black);
        btFontColor.setBackground(fontColor);
        btFontColor.invalidate();
    }//GEN-LAST:event_btFontColorActionPerformed

    private void btBackgroundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBackgroundActionPerformed
//        JColorChooser colorChooser = new JColorChooser(Color.black);
//        colorChooser.setVisible(true);
        background = JColorChooser.showDialog(getParent(), getTitle() + " background", Color.white);
        btBackground.setBackground(background);
        btBackground.invalidate();
    }//GEN-LAST:event_btBackgroundActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBackground;
    private javax.swing.JButton btCancel;
    private javax.swing.JButton btFontColor;
    private javax.swing.JButton btOk;
    private javax.swing.JComboBox cbFontSize;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbBackground;
    private javax.swing.JLabel lbFontColor;
    // End of variables declaration//GEN-END:variables
}
