/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package equa.gui.edit;

import equa.desktop.Desktop;
import equa.project.Project;
import java.io.File;
import javafx.stage.FileChooser;
import javax.swing.JFileChooser;

/**
 *
 * @author moridrin
 */
public class NewProject extends javax.swing.JFrame {

    private Project project;
    private File file;
    private final Desktop parent;

    /**
     * Creates new form NewProject
     * @param parent
     */
    public NewProject(Desktop parent) {
        initComponents();
        jLabelError.setVisible(false);
        this.parent = parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jButtonCreate = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jTextFieldCreatorRole = new javax.swing.JTextField();
        jLabelCreatorRole = new javax.swing.JLabel();
        jTextFieldProjectName = new javax.swing.JTextField();
        jLabelProjectName = new javax.swing.JLabel();
        jTextFieldCreatorName = new javax.swing.JTextField();
        jLabelCreatorName = new javax.swing.JLabel();
        jTextFieldLocation = new javax.swing.JTextField();
        jLabelLocation = new javax.swing.JLabel();
        jButtonBrowse = new javax.swing.JButton();
        jLabelError = new javax.swing.JLabel();

        jFrame1.setName("jFrame1"); // NOI18N

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Create New Project");

        jButtonCreate.setText("Create");
        jButtonCreate.setName("jButtonCreate"); // NOI18N
        jButtonCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateActionPerformed(evt);
            }
        });

        jButtonCancel.setText("Cancel");
        jButtonCancel.setName("jButtonCancel"); // NOI18N

        jTextFieldCreatorRole.setName("jTextFieldCreatorRole"); // NOI18N
        jTextFieldCreatorRole.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldFocusGained(evt);
            }
        });

        jLabelCreatorRole.setText("Role Name");
        jLabelCreatorRole.setName("jLabelCreatorRole"); // NOI18N

        jTextFieldProjectName.setName("jTextFieldProjectName"); // NOI18N
        jTextFieldProjectName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldFocusGained(evt);
            }
        });

        jLabelProjectName.setText("Project Name");
        jLabelProjectName.setName("jLabelProjectName"); // NOI18N

        jTextFieldCreatorName.setName("jTextFieldCreatorName"); // NOI18N
        jTextFieldCreatorName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldFocusGained(evt);
            }
        });

        jLabelCreatorName.setText("Creator Name");
        jLabelCreatorName.setName("jLabelCreatorName"); // NOI18N

        jTextFieldLocation.setName("jTextFieldLocation"); // NOI18N
        jTextFieldLocation.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldFocusGained(evt);
            }
        });

        jLabelLocation.setText("Location");
        jLabelLocation.setName("jLabelLocation"); // NOI18N

        jButtonBrowse.setText("...");
        jButtonBrowse.setToolTipText("Browse");
        jButtonBrowse.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButtonBrowse.setMaximumSize(new java.awt.Dimension(29, 29));
        jButtonBrowse.setMinimumSize(new java.awt.Dimension(29, 29));
        jButtonBrowse.setName("jButtonBrowse"); // NOI18N
        jButtonBrowse.setPreferredSize(new java.awt.Dimension(29, 29));
        jButtonBrowse.setSize(new java.awt.Dimension(29, 29));
        jButtonBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBrowseActionPerformed(evt);
            }
        });

        jLabelError.setForeground(new java.awt.Color(255, 0, 0));
        jLabelError.setText("Pleas fill in all fields");
        jLabelError.setName("jLabelError"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCreatorName)
                            .addComponent(jLabelProjectName)
                            .addComponent(jLabelCreatorRole)
                            .addComponent(jLabelLocation))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldProjectName)
                            .addComponent(jTextFieldCreatorName)
                            .addComponent(jTextFieldCreatorRole)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldLocation)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonBrowse, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 217, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButtonCancel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonCreate))
                            .addComponent(jLabelError, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldProjectName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelProjectName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCreatorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCreatorName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCreatorRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCreatorRole))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLocation)
                    .addComponent(jButtonBrowse, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCreate)
                    .addComponent(jButtonCancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateActionPerformed
        String projectName = jTextFieldProjectName.getText();
        String creatorName = jTextFieldCreatorName.getText();
        String creatorRole = jTextFieldCreatorRole.getText();
        String locationString = jTextFieldCreatorRole.getText();
        if (projectName.isEmpty() || creatorName.isEmpty() || creatorRole.isEmpty() || locationString.isEmpty()) {
            jLabelError.setText("Please fill in all fields");
            jLabelError.setVisible(true);
            return;
        }
        file = new File(locationString);
        project = new Project(projectName, creatorName, creatorRole, true);
        parent.createdNewProject(project, file);
    }//GEN-LAST:event_jButtonCreateActionPerformed

    private void jTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldFocusGained
        jLabelError.setVisible(false);
    }//GEN-LAST:event_jTextFieldFocusGained

    private void jButtonBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBrowseActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        int returnValue = fileChooser.showSaveDialog(NewProject.this);
        if (returnValue == JFileChooser.APPROVE_OPTION){
            file = fileChooser.getSelectedFile();
            String locationString = file.getAbsolutePath();
            if(!locationString.toLowerCase().endsWith(".sym") ) {
                file = new File(locationString + ".sym");
            }
            jTextFieldLocation.setText(file.getAbsolutePath());
        }
    }//GEN-LAST:event_jButtonBrowseActionPerformed
                                         
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBrowse;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonCreate;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabelCreatorName;
    private javax.swing.JLabel jLabelCreatorRole;
    private javax.swing.JLabel jLabelError;
    private javax.swing.JLabel jLabelLocation;
    private javax.swing.JLabel jLabelProjectName;
    private javax.swing.JTextField jTextFieldCreatorName;
    private javax.swing.JTextField jTextFieldCreatorRole;
    private javax.swing.JTextField jTextFieldLocation;
    private javax.swing.JTextField jTextFieldProjectName;
    // End of variables declaration//GEN-END:variables
}
