/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ConstrainedBaseTypeDialog.java
 *
 * Created on 17-dec-2011, 16:26:26
 */
package equa.configurator;

import javax.swing.JOptionPane;

import equa.meta.ChangeNotAllowedException;
import equa.meta.MismatchException;
import equa.meta.objectmodel.ConstrainedBaseType;
import equa.meta.objectmodel.Range;

/**
 *
 * @author frankpeeters
 */
public class ConstrainedBaseTypeDialog extends javax.swing.JDialog {

    private static final long serialVersionUID = 1L;
    private ConstrainedBaseType cbt;
    java.awt.Frame parent;

    /**
     * Creates new form ConstrainedBaseTypeDialog
     */
    public ConstrainedBaseTypeDialog(java.awt.Frame parent, boolean modal,
            ConstrainedBaseType cbt) {
        super(parent, modal);
        this.parent = parent;
        this.cbt = cbt;
        initComponents();
        tfName.setText(cbt.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        listValueConstraints = new javax.swing.JList<>();
        tfName = new javax.swing.JTextField();
        btQuit = new javax.swing.JButton();
        btAddRange = new javax.swing.JButton();
        btRemove = new javax.swing.JButton();
        btAddValue = new javax.swing.JButton();

        jDesktopPane1.setName("jDesktopPane1"); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(ConstrainedBaseTypeDialog.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N
        setResizable(false);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        listValueConstraints.setModel(cbt);
        listValueConstraints.setName("listValueConstraints"); // NOI18N
        jScrollPane1.setViewportView(listValueConstraints);

        tfName.setEditable(false);
        tfName.setText(resourceMap.getString("tfName.text")); // NOI18N
        tfName.setName("tfName"); // NOI18N

        btQuit.setText(resourceMap.getString("btQuit.text")); // NOI18N
        btQuit.setToolTipText(resourceMap.getString("btQuit.toolTipText")); // NOI18N
        btQuit.setName("btQuit"); // NOI18N
        btQuit.addActionListener(new java.awt.event.ActionListener() {
            @Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
                btQuitActionPerformed(evt);
            }
        });

        btAddRange.setText(resourceMap.getString("btAddRange.text")); // NOI18N
        btAddRange.setToolTipText(resourceMap.getString("btAddRange.toolTipText")); // NOI18N
        btAddRange.setName("btAddRange"); // NOI18N
        btAddRange.addActionListener(new java.awt.event.ActionListener() {
            @Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddRangeActionPerformed(evt);
            }
        });

        btRemove.setText(resourceMap.getString("btRemove.text")); // NOI18N
        btRemove.setToolTipText(resourceMap.getString("btRemove.toolTipText")); // NOI18N
        btRemove.setName("btRemove"); // NOI18N
        btRemove.addActionListener(new java.awt.event.ActionListener() {
            @Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoveActionPerformed(evt);
            }
        });

        btAddValue.setText(resourceMap.getString("btAddValue.text")); // NOI18N
        btAddValue.setToolTipText(resourceMap.getString("btAddValue.toolTipText")); // NOI18N
        btAddValue.setName("btAddValue"); // NOI18N
        btAddValue.addActionListener(new java.awt.event.ActionListener() {
            @Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddValueActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(tfName, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(btAddValue)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(btAddRange)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(btRemove)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(btQuit))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(tfName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(11, 11, 11)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(btRemove)
                    .add(btAddRange)
                    .add(btAddValue)
                    .add(btQuit))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAddValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddValueActionPerformed
        try {
            String result = JOptionPane.showInputDialog(getParent(), cbt,
                    "please fill in a new value",
                    JOptionPane.QUESTION_MESSAGE);
            cbt.getValueConstraint().addValue(result);
        } catch (ChangeNotAllowedException ex) {
            JOptionPane.showMessageDialog(getParent(), ex.getMessage());
        }

    }//GEN-LAST:event_btAddValueActionPerformed

    private void btAddRangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddRangeActionPerformed

        RangeDialog dialog = new RangeDialog(parent, true, cbt.getBaseType());
        dialog.setVisible(true);
        if (dialog.isOk()) {
            try {
                Range range = new Range(dialog.getLower(), dialog.getUpper());
                cbt.getValueConstraint().addRange(range);
            } catch (ChangeNotAllowedException | MismatchException ex) {
                JOptionPane.showMessageDialog(getParent(), ex.getMessage());
            }
        }
    }//GEN-LAST:event_btAddRangeActionPerformed

    private void btRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoveActionPerformed
        Object object = listValueConstraints.getSelectedValue();
        if (object != null) {
            cbt.getValueConstraint().removeValue(object.toString());
        }
    }//GEN-LAST:event_btRemoveActionPerformed

    private void btQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btQuitActionPerformed
        setVisible(false);
    }//GEN-LAST:event_btQuitActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAddRange;
    private javax.swing.JButton btAddValue;
    private javax.swing.JButton btQuit;
    private javax.swing.JButton btRemove;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<Object> listValueConstraints;
    private javax.swing.JTextField tfName;
    // End of variables declaration//GEN-END:variables
}
