/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package equa.configurator;

import equa.meta.objectmodel.ConstrainedBaseType;
import equa.meta.objectmodel.ObjectRole;
import equa.meta.objectmodel.ObjectType;
import equa.meta.objectmodel.TypeExpression;
import java.awt.Component;
import java.awt.Container;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.text.JTextComponent;

/**
 *
 * @author frankpeeters
 */
public class DefaultValueDialog extends javax.swing.JDialog {

    private static final long serialVersionUID = 1L;
    private ObjectType vt;
    private boolean defined;

    /**
     * Creates new form DefaultValueDialog
     */
    public DefaultValueDialog(java.awt.Frame parent, ObjectRole role) {
        super(parent, true);
        initComponents();
        this.vt = role.getSubstitutionType();
        setTitle("Default value of " + role.detectRoleName());
        myInit();
    }

    void myInit() {

        panelTE.setLayout(new GridLayout(2 * vt.getFactType().getSize() + 1, 1));
        TypeExpression te = vt.getOTE();
        JLabel label = new JLabel(te.constant(0));
        panelTE.add(label);
        for (int i = 0; i < te.getParent().getSize(); i++) {
            JTextField tf = new JTextField();
            panelTE.add(tf);
            label = new JLabel(te.constant(i + 1));
            panelTE.add(label);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTE = new javax.swing.JPanel();
        panelButtons = new javax.swing.JPanel();
        btOK = new javax.swing.JButton();
        btCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelTE.setName("panelTE"); // NOI18N

        javax.swing.GroupLayout panelTELayout = new javax.swing.GroupLayout(panelTE);
        panelTE.setLayout(panelTELayout);
        panelTELayout.setHorizontalGroup(
            panelTELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        panelTELayout.setVerticalGroup(
            panelTELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 182, Short.MAX_VALUE)
        );

        getContentPane().add(panelTE, java.awt.BorderLayout.CENTER);

        panelButtons.setName("panelButtons"); // NOI18N

        btOK.setText("OK");
        btOK.setName("btOK"); // NOI18N
        btOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOKActionPerformed(evt);
            }
        });

        btCancel.setText("Cancel");
        btCancel.setName("btCancel"); // NOI18N
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelButtonsLayout = new javax.swing.GroupLayout(panelButtons);
        panelButtons.setLayout(panelButtonsLayout);
        panelButtonsLayout.setHorizontalGroup(
            panelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelButtonsLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(btOK)
                .addGap(18, 18, 18)
                .addComponent(btCancel)
                .addContainerGap(168, Short.MAX_VALUE))
        );
        panelButtonsLayout.setVerticalGroup(
            panelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelButtonsLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(panelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btOK)
                    .addComponent(btCancel))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        getContentPane().add(panelButtons, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOKActionPerformed

        defined = true;
        for (int i=0;i<vt.getFactType().getSize();i++){
                if((((JTextField)panelTE.getComponent(2*i+1)).getText()).trim().isEmpty()){
                    JOptionPane.showMessageDialog(this, "empty substitution is not allowed");
                    defined=false;
                }
            }
        setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_btOKActionPerformed

    private void btCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelActionPerformed
        defined = false;
        setVisible(false);
    }//GEN-LAST:event_btCancelActionPerformed

    List<String> getValues() {
        if (defined) {
            List<String> values = new ArrayList<String>();
            for (int i=0;i<vt.getFactType().getSize();i++){
                values.add(((JTextField)panelTE.getComponent(2*i+1)).getText());
               
            }
            return values;
        } else {
            return null;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancel;
    private javax.swing.JButton btOK;
    private javax.swing.JPanel panelButtons;
    private javax.swing.JPanel panelTE;
    // End of variables declaration//GEN-END:variables
}
