/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package equa.configurator;

import equa.meta.ChangeNotAllowedException;
import equa.meta.objectmodel.FactType;
import equa.meta.objectmodel.ObjectModel;
import equa.meta.requirements.RequirementModel;
import equa.meta.requirements.RuleRequirement;
import equa.meta.traceability.Category;
import equa.meta.traceability.ExternalInput;
import equa.project.Project;
import equa.project.ProjectRole;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author frankpeeters
 */
public class DerivableDialog extends javax.swing.JDialog {

    private FactType ft;

    /**
     * Creates new form DerivableDialog
     */
    public DerivableDialog(java.awt.Frame parent, FactType ft) {
        super(parent, true);
        this.ft = ft;
        initComponents();
        initControls();
        setTitle("Derivable Constraint");
    }

    void initControls() {
        btDelete.setEnabled(ft.isDerivable());
        if (ft.isDerivable()) {
            taText.setText(ft.getDerivableText());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btOk = new javax.swing.JButton();
        btCancel = new javax.swing.JButton();
        btDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taText = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btOk.setText("OK");
        btOk.setName("btOk"); // NOI18N
        btOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOkActionPerformed(evt);
            }
        });

        btCancel.setText("Cancel");
        btCancel.setName("btCancel"); // NOI18N
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelActionPerformed(evt);
            }
        });

        btDelete.setText("Delete");
        btDelete.setName("btDelete"); // NOI18N
        btDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteActionPerformed(evt);
            }
        });

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        taText.setColumns(20);
        taText.setLineWrap(true);
        taText.setRows(5);
        taText.setWrapStyleWord(true);
        taText.setName("taText"); // NOI18N
        jScrollPane1.setViewportView(taText);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btDelete)
                        .addGap(18, 18, 18)
                        .addComponent(btOk)
                        .addGap(18, 18, 18)
                        .addComponent(btCancel)
                        .addGap(0, 6, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btOk)
                    .addComponent(btDelete)
                    .addComponent(btCancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelActionPerformed
        taText.setText("");
        setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_btCancelActionPerformed

    private void btOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOkActionPerformed
        if (taText.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "derivable text can not be empty");
        } else {
            Project project = ((ObjectModel) ft.getParent()).getProject();
            ProjectRole role = project.getCurrentUser();
            try {
                if (ft.isDerivable()) {
                    ft.getDerivableConstraint().setText(new ExternalInput("", role), taText.getText());
                } else {
                    RequirementModel rm = project.getRequirementModel();
                    if (ft.isElementary()){
                    RuleRequirement rule = rm.addRuleRequirement(ft.getCategory(), taText.getText(),
                        new ExternalInput("", role));
                    ft.addDerivableConstraint(rule, taText.getText());}
                    else {
                        JOptionPane.showMessageDialog(this,"fact type isn't elementary");
                    }
                }
                
            } catch (ChangeNotAllowedException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
             setVisible(false);
        }
       
    }//GEN-LAST:event_btOkActionPerformed

    private void btDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteActionPerformed
        ft.getDerivableConstraint().remove();
        setVisible(false);
    }//GEN-LAST:event_btDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancel;
    private javax.swing.JButton btDelete;
    private javax.swing.JButton btOk;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea taText;
    // End of variables declaration//GEN-END:variables
}
