/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewObjectTypeDialog.java
 *
 * Created on 25-okt-2012, 14:32:16
 */
package equa.configurator;

import java.awt.HeadlessException;
import java.util.ArrayList;
import java.util.List;

import javax.swing.JOptionPane;

import equa.meta.ChangeNotAllowedException;
import equa.meta.DuplicateException;
import equa.meta.MismatchException;
import equa.meta.objectmodel.FactType;
import equa.meta.objectmodel.ObjectModel;
import equa.meta.objectmodel.Role;
import equa.meta.objectmodel.SubstitutionType;
import equa.meta.traceability.Source;
import equa.project.ProjectRole;

/**
 *
 * @author frankpeeters
 */
public class NewObjectTypeDialog extends javax.swing.JDialog {

    private static final long serialVersionUID = 1L;
    private ObjectModel om;
    private List<Role> roles;
    private List<Source> sources;
    private FactType ft;
    private ProjectRole currentUser;

    /**
     * Creates new form NewObjectTypeDialog
     */
    public NewObjectTypeDialog(java.awt.Frame parent, boolean modal, ObjectModel om, List<Role> roles, List<Source> sources,
            ProjectRole currentUser) {
        super(parent, modal);
        initComponents();
        this.om = om;
        this.roles = roles;
        this.sources = sources;
        this.ft = null;
        this.currentUser = currentUser;
        btClose.setEnabled(false);
        setTitle("Creation of a new object type with expression");
    }

    private void closeDialog() throws HeadlessException {
        if (ft == null) {
            JOptionPane.showMessageDialog(this, "creation of new object type has not been realized");
        }
        setVisible(false);
    }

    public FactType getNewFactType() {
        return ft;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfObjectTypeName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btEditTE = new javax.swing.JButton();
        btClose = new javax.swing.JButton();
        btHelp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(NewObjectTypeDialog.class);
        tfObjectTypeName.setText(resourceMap.getString("tfObjectTypeName.text")); // NOI18N
        tfObjectTypeName.setName("tfObjectTypeName"); // NOI18N
        tfObjectTypeName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfObjectTypeNameActionPerformed(evt);
            }
        });

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        btEditTE.setText(resourceMap.getString("btEditTE.text")); // NOI18N
        btEditTE.setName("btEditTE"); // NOI18N
        btEditTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditTEActionPerformed(evt);
            }
        });

        btClose.setText(resourceMap.getString("btClose.text")); // NOI18N
        btClose.setName("btClose"); // NOI18N
        btClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCloseActionPerformed(evt);
            }
        });

        btHelp.setText(resourceMap.getString("btHelp.text")); // NOI18N
        btHelp.setName("btHelp"); // NOI18N
        btHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHelpActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(9, 9, 9)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(tfObjectTypeName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 181, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel1))
                    .add(layout.createSequentialGroup()
                        .add(btEditTE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 137, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 63, Short.MAX_VALUE)
                        .add(btClose)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(btHelp)))
                .addContainerGap(38, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(24, 24, 24)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(tfObjectTypeName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel1))
                .add(3, 3, 3)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(btEditTE)
                    .add(btHelp)
                    .add(btClose))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btEditTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditTEActionPerformed
        if (tfObjectTypeName.getText().isEmpty()) {
            JOptionPane.showMessageDialog(getParent(), "please enter an unique name for the new object type");
        } else {
            if (om.getFactType(tfObjectTypeName.getText()) != null) {
                JOptionPane.showMessageDialog(getParent(), "the entered name for the new object type already exists");
            } else {
                EditTypeExpressionDialog dialog = new EditTypeExpressionDialog((java.awt.Frame) getParent(), roles,
                        "Edit Object Type Expression", currentUser);
                dialog.setVisible(true);

                List<SubstitutionType> sts = new ArrayList<>();
                List<String> rolenames = new ArrayList<>();
                List<Integer> rolenumbers = new ArrayList<>(roles.size());
                int i = 0;
                for (Role role : dialog.getRoles()) {
                    sts.add(role.getSubstitutionType());
                    rolenames.add(role.getRoleName());
                    rolenumbers.add(i);
                    i++;
                }
                try {
                    ft = om.addObjectType(tfObjectTypeName.getText(), dialog.getConstants(), sts, rolenames, rolenumbers, sources);
                    ft.injectLocalConstraints(dialog.getRoles());
                    btClose.setEnabled(true);
                    btClose.requestFocus();
                } catch (MismatchException | ChangeNotAllowedException | DuplicateException ex) {
                    JOptionPane.showMessageDialog(this, ex.getMessage());
                    ft = null;
                }

            }

        }
    }//GEN-LAST:event_btEditTEActionPerformed

    private void btCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCloseActionPerformed
        closeDialog();
    }//GEN-LAST:event_btCloseActionPerformed

    private void btHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHelpActionPerformed
        JOptionPane.showMessageDialog(this, ""
                + "step 1: Choose a unique name.\n"
                + "step 2: Press the Edit-button.\n");
    }//GEN-LAST:event_btHelpActionPerformed

    private void btCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelActionPerformed
        // TODO add your handling code here:
        closeDialog();
    }//GEN-LAST:event_btCancelActionPerformed

    private void tfObjectTypeNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfObjectTypeNameActionPerformed
        btEditTEActionPerformed(evt);  
    }//GEN-LAST:event_tfObjectTypeNameActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btClose;
    private javax.swing.JButton btEditTE;
    private javax.swing.JButton btHelp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField tfObjectTypeName;
    // End of variables declaration//GEN-END:variables
}
